### ISSUE TITLE
Challenge log layout suggestion

### ISSUE THREAD

**Issue by benz145** [trescenzi/checkin-viz#14]
A mockup from a while ago, putting it here so we have everything in one place.

![challenge-layout-concept](https://github.com/user-attachments/assets/518ec48e-3a05-42dd-8f12-a5fb6049911d)

Explanation:

- **List sort:** Sorted by 'Overall Points' (total POINTS for the challenge, not just the week)
- **Points next to names:** The points for that week only
- **Overall > Points:** Points for the whole challenge
- **Overall > Check-ins bars:** Progress bar indicating number of check-ins compared to total possible check-ins overall (ie: if the person has 25% of the total possible check-ins for the challenge, the bar should be 25% full).

**Comment by trescenzi** [comment]
i'm going to call this closed since we're here and there's another to improve it yet again
