### ISSUE TITLE
Allow math inside calculator fields

### ISSUE THREAD

**Issue by benz145** [trescenzi/checkin-viz#2]
Every day that I check in I use a calculator to add my minutes up from different exercises, then I put that number into the Tier Calculator. It would be awesome if I could do the math directly in the calculator field and have it added for me. 

![image](https://github.com/trescenzi/checkin-viz/assets/12601485/a80dcc3d-ae97-44eb-b8e0-5ca1bc07bd56)

This might conflict with the PIN/numpad keyboard on iPhone. Maybe there’s another version that includes the basic calculator operators like plus and minus? Or you could do an on-page calculator style input?

**Comment by benz145** [comment]
Can we also add support for subtraction? Less likely to be used but I could see situations where someone would want to use it (and they would expect it would be supported if addition is)

**Comment by trescenzi** [comment]
I can't think of a reason that it would be useful but it's not hard to support.
