### ISSUE TITLE
Add numpad with operators to Tier Calculator

### ISSUE THREAD

**Issue by benz145** [trescenzi/checkin-viz#6]
Looks like there is a way to get a numpad keyboard with operator symbols on iOS. 

![image](https://github.com/trescenzi/checkin-viz/assets/12601485/85bd3b2f-88f0-4dff-bd62-99e6fd979be1)

Looks like input type [decimal] or [tel] might get us what we want.

![image](https://github.com/trescenzi/checkin-viz/assets/12601485/189304bb-e2fb-499b-b60b-b6ce37ca7d36)

@trescenzi This is probably the kind of thing I could play with in the code myself to find out if it worked, if there was a way for me to test the output. But I have to imagine it would be a whole lot of extra work to make that possible?

**Comment by trescenzi** [comment]
Switched to tel keyboard

**Comment by benz145** [comment]
Confirmed working for me!
